{{- if not .Values.ibkr.credentials.existingSecret }}
{{- if or .Values.ibkr.gateways.paper.enabled .Values.ibkr.gateways.live.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ibkrtrader.fullname" . }}-ibkr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ibkrtrader.labels" . | nindent 4 }}
type: Opaque
stringData:
  TWS_USERID: {{ .Values.ibkr.credentials.username | default "REPLACE_ME" | quote }}
  TWS_PASSWORD: {{ .Values.ibkr.credentials.password | default "REPLACE_ME" | quote }}
{{- end }}
{{- end }}
